<?php

/**
 * @file
 * Mathematical text formatter hooks.
 */

/**
 * Implements hook_theme().
 */
function math_formatter_theme() {
  return [
    'math_formatter' => [
      'variables' => ['evaluate' => 'sync', 'value' => ''],
      'template' => 'math_formatter',
    ],
    'react_math_formatter' => [
      'variables' => ['bundle' => '', 'field_name' => '', 'nid' => ''],
      'template' => 'react_math_formatter',
     ],
  ];
}

/**
 * Implements hook_uninstall().
 */
function math_formatter_uninstall() {
  // Removes the configuration introduced to prevent 'Missing plugin'
  // error on module uninstall.
  \Drupal::configFactory()->getEditable('rest.resource.calculator_resource')->delete();
}
