<?php

/**
 * @file
 * Mathematical text formatter hooks.
 */

/**
 * Implements hook_theme().
 */
function math_formatter_theme() {
  return [
    'math_formatter' => [
      'variables' => ['value' => '', 'evaluate' => 'sync'],
      'template' => 'math_formatter',
    ],
  ];
}

/**
 * Implements hook_uninstall().
 */
function math_formatter_uninstall() {
  \Drupal::configFactory()->getEditable('rest.resource.calculator_resource')->delete();
}
